steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/basic-dispatch-376816/test:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/basic-dispatch-376816/test:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'test', '--region=europe-west1', '--platform=managed','--image=gcr.io/basic-dispatch-376816/test:$SHORT_SHA']
  
